global:
  scrape_interval: 15s       # How often to pull the metrics
  evaluation_interval: 15s 

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Scrape the node exporters
  - job_name: "nodes" # Groups the node exporters together 
    static_configs:
      - targets:
          - "node-1:9100"
          - "node-2:9100"
          - "node-3:9100"
        labels:
          cluster: "dev"
