global:
  scrape_interval: 15s       # How often to pull the metrics
  evaluation_interval: 15s

# Tell prom where alertmanager is
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Scrape cAdvisor for per-container metrics
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # Scrape the node exporters
  - job_name: "nodes" # Groups the node exporters together
    static_configs:
      - targets:
          - "node-1:9100"
          - "node-2:9100"
          - "node-3:9100"
        labels:
          cluster: "dev"
